# Flutter KeyCheck Configuration
# This file configures the validation behavior for CI/CD pipelines

# Project settings
project_root: "."
include_example_folders: true

# Key filtering
include_patterns:
  - "**/*.dart"
exclude_patterns:
  - "**/generated/**"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/test_data/**"

# Validation settings
fail_on_lost_keys: true
fail_on_renamed_keys: true
max_drift_percentage: 10

# Performance settings
parallel_processing: true
cache_analysis_results: true

# Output settings
default_output_format: "json"
generate_html_reports: true

# CI-specific settings
ci_mode:
  enabled: true
  performance_benchmarks: true
  detailed_reports: true
  
# Tracked keys - subset of critical keys to monitor
tracked_keys:
  - "login_button"
  - "password_field"
  - "submit_form"
  - "navigation_menu"
  - "main_content"
  - "error_dialog"
  - "loading_indicator"
  - "settings_button"