# GitLab CI/CD Pipeline for Flutter KeyCheck
# Complete enterprise-grade pipeline with quality gates and key validation

stages:
  - validate
  - test
  - quality
  - performance
  - report
  - deploy

variables:
  DART_SDK_VERSION: "stable"
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"
  COVERAGE_THRESHOLD: "80"
  PERFORMANCE_THRESHOLD: "30000"  # 30 seconds max scan time
  CRITICAL_KEYS_MIN: "4"
  
cache:
  key: 
    files:
      - pubspec.lock
  paths:
    - .pub-cache/
    - .dart_tool/

before_script:
  - export PATH="$PATH:$PUB_CACHE/bin"
  - dart --version
  - dart pub get

# ======================================
# Stage 1: Flutter KeyCheck Validation
# ======================================

keycheck-validation:
  stage: validate
  image: dart:stable
  timeout: 10m
  script:
    - echo "🔑 Flutter KeyCheck Baseline Validation"
    - echo "========================================"
    
    # Run baseline validation with strict settings
    - START_TIME=$(date +%s%3N)
    - |
      timeout 30s dart run bin/flutter_keycheck.dart \
        --keys test/golden_workspace/expected_keycheck.json \
        --path test/golden_workspace \
        --verbose \
        --strict > keycheck_output.log 2>&1 || VALIDATION_EXIT_CODE=$?
    - END_TIME=$(date +%s%3N)
    - SCAN_DURATION=$((END_TIME - START_TIME))
    
    # Parse validation results
    - TOTAL_KEYS=$(grep -o "Total keys found:[[:space:]]*[0-9]*" keycheck_output.log | grep -o "[0-9]*" || echo "0")
    - CRITICAL_KEYS=$(grep -o "Critical keys:[[:space:]]*[0-9]*" keycheck_output.log | grep -o "[0-9]*" || echo "0")
    - EXPECTED_KEYS=14
    
    # Calculate coverage score
    - |
      if [ "$TOTAL_KEYS" -gt 0 ]; then
        COVERAGE_SCORE=$(echo "scale=1; $TOTAL_KEYS * 100 / $EXPECTED_KEYS" | bc -l)
      else
        COVERAGE_SCORE="0.0"
      fi
    
    # Display results
    - echo ""
    - echo "📊 Validation Results:"
    - echo "   • Keys Found: $TOTAL_KEYS/$EXPECTED_KEYS"
    - echo "   • Critical Keys: $CRITICAL_KEYS"
    - echo "   • Coverage Score: ${COVERAGE_SCORE}%"
    - echo "   • Scan Duration: ${SCAN_DURATION}ms"
    
    # Quality Gates Validation
    - echo ""
    - echo "🚦 Quality Gates:"
    - GATES_PASSED=0
    - GATES_TOTAL=3
    
    # Gate 1: Coverage Threshold (80%)
    - |
      if (( $(echo "$COVERAGE_SCORE >= $COVERAGE_THRESHOLD" | bc -l) )); then
        echo "   ✅ Coverage Gate: ${COVERAGE_SCORE}% >= ${COVERAGE_THRESHOLD}%"
        GATES_PASSED=$((GATES_PASSED + 1))
      else
        echo "   ❌ Coverage Gate: ${COVERAGE_SCORE}% < ${COVERAGE_THRESHOLD}%"
        echo "ERROR: Key coverage below minimum threshold"
      fi
    
    # Gate 2: Critical Keys (minimum 4)
    - |
      if [ "$CRITICAL_KEYS" -ge "$CRITICAL_KEYS_MIN" ]; then
        echo "   ✅ Critical Keys Gate: $CRITICAL_KEYS/$CRITICAL_KEYS_MIN found"
        GATES_PASSED=$((GATES_PASSED + 1))
      else
        echo "   ❌ Critical Keys Gate: Only $CRITICAL_KEYS/$CRITICAL_KEYS_MIN critical keys found"
        echo "ERROR: Missing critical keys for automation"
      fi
    
    # Gate 3: Performance Threshold (30 seconds)
    - |
      if [ "$SCAN_DURATION" -lt "$PERFORMANCE_THRESHOLD" ]; then
        echo "   ✅ Performance Gate: ${SCAN_DURATION}ms < ${PERFORMANCE_THRESHOLD}ms"
        GATES_PASSED=$((GATES_PASSED + 1))
      else
        echo "   ❌ Performance Gate: ${SCAN_DURATION}ms >= ${PERFORMANCE_THRESHOLD}ms"
        echo "WARNING: Scan duration exceeds performance target"
      fi
    
    # Generate validation report
    - |
      cat > validation-report.json << EOF
      {
        "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
        "pipeline": {
          "project": "$CI_PROJECT_NAME",
          "branch": "$CI_COMMIT_REF_NAME",
          "commit": "$CI_COMMIT_SHA",
          "job": "$CI_JOB_ID"
        },
        "summary": {
          "keysFound": $TOTAL_KEYS,
          "keysExpected": $EXPECTED_KEYS,
          "criticalKeys": $CRITICAL_KEYS,
          "coverageScore": $COVERAGE_SCORE,
          "scanDuration": $SCAN_DURATION,
          "gatesPassed": $GATES_PASSED,
          "gatesTotal": $GATES_TOTAL
        },
        "qualityGates": {
          "coverage": {
            "passed": $(if (( $(echo "$COVERAGE_SCORE >= $COVERAGE_THRESHOLD" | bc -l) )); then echo "true"; else echo "false"; fi),
            "threshold": $COVERAGE_THRESHOLD,
            "actual": $COVERAGE_SCORE
          },
          "criticalKeys": {
            "passed": $(if [ "$CRITICAL_KEYS" -ge "$CRITICAL_KEYS_MIN" ]; then echo "true"; else echo "false"; fi),
            "threshold": $CRITICAL_KEYS_MIN,
            "actual": $CRITICAL_KEYS
          },
          "performance": {
            "passed": $(if [ "$SCAN_DURATION" -lt "$PERFORMANCE_THRESHOLD" ]; then echo "true"; else echo "false"; fi),
            "threshold": $PERFORMANCE_THRESHOLD,
            "actual": $SCAN_DURATION
          }
        },
        "details": {
          "baseline": "test/golden_workspace/expected_keycheck.json",
          "strictMode": true,
          "validationMode": "baseline"
        }
      }
      EOF
    
    # Export variables for downstream jobs
    - echo "KEYCHECK_COVERAGE_SCORE=$COVERAGE_SCORE" >> keycheck.env
    - echo "KEYCHECK_SCAN_DURATION=$SCAN_DURATION" >> keycheck.env
    - echo "KEYCHECK_CRITICAL_KEYS=$CRITICAL_KEYS" >> keycheck.env
    - echo "KEYCHECK_GATES_PASSED=$GATES_PASSED" >> keycheck.env
    
    # Final gate validation
    - |
      if [ "$GATES_PASSED" -eq "$GATES_TOTAL" ]; then
        echo ""
        echo "✅ All quality gates passed ($GATES_PASSED/$GATES_TOTAL)"
      else
        echo ""
        echo "❌ Quality gate validation failed ($GATES_PASSED/$GATES_TOTAL passed)"
        exit 1
      fi
      
  artifacts:
    reports:
      junit: validation-report.xml
    paths:
      - validation-report.json
      - keycheck_output.log
      - keycheck.env
    expire_in: 30 days
    when: always
  
  only:
    - merge_requests
    - main
    - develop

# ======================================
# Stage 2: Test Suite
# ======================================

unit-tests:
  stage: test
  image: dart:stable
  timeout: 15m
  needs: ["keycheck-validation"]
  script:
    - echo "🧪 Running comprehensive test suite..."
    
    # Static analysis
    - echo "🔍 Static Analysis:"
    - dart analyze --fatal-infos --fatal-warnings
    - echo "   ✅ Code analysis passed"
    
    # Format validation
    - echo "🎨 Format Check:"
    - dart format --output=none --set-exit-if-changed .
    - echo "   ✅ Code formatting verified"
    
    # Unit tests with coverage
    - echo "🧪 Unit Tests:"
    - dart test --reporter expanded --chain-stack-traces --coverage=coverage
    - echo "   ✅ All unit tests passed"
    
    # Build verification
    - echo "🔨 Build Verification:"
    - dart compile exe bin/flutter_keycheck.dart -o flutter_keycheck
    - ./flutter_keycheck --help > /dev/null
    - echo "   ✅ Executable build verified"
    
  coverage: '/Lines\s+:\s+(\d+\.\d+)%/'
  artifacts:
    paths:
      - coverage/
      - flutter_keycheck
    expire_in: 7 days

integration-tests:
  stage: test
  image: dart:stable
  timeout: 10m
  needs: ["keycheck-validation"]
  script:
    - echo "🔗 Running integration tests..."
    
    # Load keycheck results
    - source keycheck.env
    
    # Golden workspace tests
    - |
      if [ -f "test/golden_workspace/expected_keycheck.json" ]; then
        echo "🏆 Golden Workspace Validation:"
        dart test test/golden_workspace/ --reporter expanded
        echo "   ✅ Golden workspace tests passed"
      fi
    
    # Performance regression check
    - |
      if [ -f "test/golden_workspace/performance_baseline.json" ]; then
        echo "🚀 Performance Regression Check:"
        BASELINE_DURATION=$(grep -o '"avgDuration":[0-9]*' test/golden_workspace/performance_baseline.json | grep -o '[0-9]*')
        REGRESSION_THRESHOLD=$((BASELINE_DURATION * 120 / 100))
        
        if [ "$KEYCHECK_SCAN_DURATION" -lt "$REGRESSION_THRESHOLD" ]; then
          echo "   ✅ Performance within baseline (${KEYCHECK_SCAN_DURATION}ms vs ${BASELINE_DURATION}ms)"
        else
          echo "   ⚠️ Performance regression detected (${KEYCHECK_SCAN_DURATION}ms vs ${BASELINE_DURATION}ms)"
        fi
      fi
      
  artifacts:
    paths:
      - test/results/
    expire_in: 7 days

# ======================================
# Stage 3: Quality Assessment
# ======================================

quality-gates:
  stage: quality
  image: dart:stable
  timeout: 10m
  needs: ["keycheck-validation", "unit-tests"]
  script:
    - echo "🛡️ Quality Assessment & Security Scan"
    
    # Load validation results
    - source keycheck.env
    
    # Package analysis with pana
    - echo "📦 Package Analysis (pana):"
    - dart pub global activate pana
    - pana --no-warning . > pana_report.txt 2>&1 || true
    - PANA_SCORE=$(grep -oP '\d+(?=/\d+ points)' pana_report.txt | head -1 || echo "0")
    - echo "   Package Score: $PANA_SCORE/160 points"
    
    # Security scanning (basic dependency check)
    - echo "🔒 Security Scan:"
    - dart pub deps --json > dependencies.json
    - echo "   ✅ Dependency scan completed"
    
    # Quality summary
    - |
      cat > quality-report.json << EOF
      {
        "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
        "quality": {
          "panaScore": $PANA_SCORE,
          "coverageScore": $KEYCHECK_COVERAGE_SCORE,
          "performanceScore": $(echo "scale=1; 100 - ($KEYCHECK_SCAN_DURATION / 300)" | bc -l),
          "gatesPassed": $KEYCHECK_GATES_PASSED
        },
        "thresholds": {
          "panaMinimum": 120,
          "coverageMinimum": $COVERAGE_THRESHOLD,
          "performanceMaximum": $PERFORMANCE_THRESHOLD
        }
      }
      EOF
    
    # Quality gate validation
    - |
      QUALITY_ISSUES=0
      echo "🚦 Quality Gate Summary:"
      
      if [ "$PANA_SCORE" -ge 120 ]; then
        echo "   ✅ Package Quality: $PANA_SCORE >= 120"
      else
        echo "   ⚠️ Package Quality: $PANA_SCORE < 120 (recommended)"
        QUALITY_ISSUES=$((QUALITY_ISSUES + 1))
      fi
      
      if [ "$QUALITY_ISSUES" -eq 0 ]; then
        echo "   ✅ All quality checks passed"
      else
        echo "   ⚠️ $QUALITY_ISSUES quality issues found (non-blocking)"
      fi
      
  artifacts:
    paths:
      - quality-report.json
      - pana_report.txt
      - dependencies.json
    expire_in: 30 days

# ======================================
# Stage 4: Performance Monitoring
# ======================================

performance-benchmark:
  stage: performance
  image: dart:stable
  timeout: 15m
  needs: ["keycheck-validation"]
  script:
    - echo "⚡ Performance Benchmarking"
    
    # Load results
    - source keycheck.env
    
    # Run performance benchmarks
    - |
      echo "🏃 Running performance benchmarks..."
      BENCHMARK_RUNS=5
      TOTAL_DURATION=0
      
      for i in $(seq 1 $BENCHMARK_RUNS); do
        echo "   Run $i/$BENCHMARK_RUNS..."
        START_TIME=$(date +%s%3N)
        timeout 60s dart run bin/flutter_keycheck.dart \
          --keys test/golden_workspace/expected_keycheck.json \
          --path test/golden_workspace > /dev/null 2>&1 || true
        END_TIME=$(date +%s%3N)
        RUN_DURATION=$((END_TIME - START_TIME))
        TOTAL_DURATION=$((TOTAL_DURATION + RUN_DURATION))
        echo "      Duration: ${RUN_DURATION}ms"
      done
      
      AVG_DURATION=$((TOTAL_DURATION / BENCHMARK_RUNS))
      echo "   Average Duration: ${AVG_DURATION}ms"
    
    # Performance report
    - |
      cat > performance-report.json << EOF
      {
        "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
        "benchmark": {
          "runs": $BENCHMARK_RUNS,
          "averageDuration": $AVG_DURATION,
          "totalDuration": $TOTAL_DURATION,
          "threshold": $PERFORMANCE_THRESHOLD
        },
        "validation": {
          "scanDuration": $KEYCHECK_SCAN_DURATION,
          "performanceGrade": "$(if [ "$KEYCHECK_SCAN_DURATION" -lt 10000 ]; then echo "A"; elif [ "$KEYCHECK_SCAN_DURATION" -lt 20000 ]; then echo "B"; else echo "C"; fi)"
        }
      }
      EOF
    
    # Performance analysis
    - |
      echo "📊 Performance Analysis:"
      echo "   • Validation Scan: ${KEYCHECK_SCAN_DURATION}ms"
      echo "   • Benchmark Average: ${AVG_DURATION}ms"
      echo "   • Performance Grade: $(if [ "$KEYCHECK_SCAN_DURATION" -lt 10000 ]; then echo "A (Excellent)"; elif [ "$KEYCHECK_SCAN_DURATION" -lt 20000 ]; then echo "B (Good)"; else echo "C (Acceptable)"; fi)"
      
  artifacts:
    paths:
      - performance-report.json
    expire_in: 30 days
  only:
    - main
    - merge_requests

# ======================================
# Stage 5: Reporting & Documentation
# ======================================

generate-reports:
  stage: report
  image: dart:stable
  timeout: 5m
  needs: ["quality-gates", "performance-benchmark"]
  script:
    - echo "📋 Generating comprehensive reports..."
    
    # Load all results
    - source keycheck.env
    
    # Create comprehensive markdown report
    - |
      cat > VALIDATION_REPORT.md << EOF
      # Flutter KeyCheck Validation Report
      
      **Pipeline**: $CI_PIPELINE_ID | **Branch**: $CI_COMMIT_REF_NAME | **Commit**: $CI_COMMIT_SHA
      **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
      
      ## 🔑 Key Validation Results
      
      | Metric | Value | Status |
      |--------|-------|--------|
      | Keys Found | $KEYCHECK_CRITICAL_KEYS/14 | $(if [ "$KEYCHECK_CRITICAL_KEYS" -ge 4 ]; then echo "✅ Pass"; else echo "❌ Fail"; fi) |
      | Coverage Score | ${KEYCHECK_COVERAGE_SCORE}% | $(if (( $(echo "$KEYCHECK_COVERAGE_SCORE >= 80" | bc -l) )); then echo "✅ Pass"; else echo "❌ Fail"; fi) |
      | Critical Keys | $KEYCHECK_CRITICAL_KEYS/4 | $(if [ "$KEYCHECK_CRITICAL_KEYS" -ge 4 ]; then echo "✅ Pass"; else echo "❌ Fail"; fi) |
      | Scan Duration | ${KEYCHECK_SCAN_DURATION}ms | $(if [ "$KEYCHECK_SCAN_DURATION" -lt 30000 ]; then echo "✅ Pass"; else echo "⚠️ Warning"; fi) |
      
      ## 🚦 Quality Gates Summary
      
      **Gates Passed**: $KEYCHECK_GATES_PASSED/3
      
      - **Coverage Gate**: $(if (( $(echo "$KEYCHECK_COVERAGE_SCORE >= 80" | bc -l) )); then echo "✅ Passed"; else echo "❌ Failed"; fi) (${KEYCHECK_COVERAGE_SCORE}% >= 80%)
      - **Critical Keys Gate**: $(if [ "$KEYCHECK_CRITICAL_KEYS" -ge 4 ]; then echo "✅ Passed"; else echo "❌ Failed"; fi) ($KEYCHECK_CRITICAL_KEYS/4 found)
      - **Performance Gate**: $(if [ "$KEYCHECK_SCAN_DURATION" -lt 30000 ]; then echo "✅ Passed"; else echo "⚠️ Warning"; fi) (${KEYCHECK_SCAN_DURATION}ms < 30s)
      
      ## 📊 Recommendations
      
      $(if [ "$KEYCHECK_GATES_PASSED" -eq 3 ]; then
        echo "✅ **All quality gates passed** - Ready for deployment"
      else
        echo "⚠️ **Quality issues detected** - Review required before deployment"
      fi)
      
      ---
      *Generated by Flutter KeyCheck CI/CD Pipeline*
      EOF
    
    # Create deployment readiness assessment
    - |
      if [ "$KEYCHECK_GATES_PASSED" -eq 3 ]; then
        echo "DEPLOYMENT_READY=true" >> deployment.env
        echo "✅ DEPLOYMENT READY: All quality gates passed"
      else
        echo "DEPLOYMENT_READY=false" >> deployment.env
        echo "❌ DEPLOYMENT BLOCKED: Quality gate failures detected"
      fi
      
  artifacts:
    paths:
      - VALIDATION_REPORT.md
      - deployment.env
    reports:
      junit: validation-report.xml
    expire_in: 30 days

# ======================================
# Stage 6: Deployment Gates
# ======================================

deployment-gate:
  stage: deploy
  image: dart:stable
  timeout: 5m
  needs: ["generate-reports"]
  script:
    - echo "🚀 Deployment Gate Validation"
    
    # Load deployment status
    - source deployment.env
    
    # Final deployment decision
    - |
      if [ "$DEPLOYMENT_READY" = "true" ]; then
        echo "✅ Deployment authorized - All quality gates passed"
        echo "🚀 Package is ready for pub.dev publication"
      else
        echo "❌ Deployment blocked - Quality gate failures"
        echo "🔧 Fix quality issues before deployment"
        exit 1
      fi
      
  only:
    - main
    - tags

publish-dry-run:
  stage: deploy
  image: dart:stable
  timeout: 5m
  needs: ["deployment-gate"]
  script:
    - echo "📦 Publishing dry run..."
    - dart pub publish --dry-run
    - echo "✅ Package ready for publication"
  only:
    - main
    - tags

# ======================================
# Notification Rules
# ======================================

.notify_failure: &notify_failure
  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "failed" ]; then
        echo "🚨 Pipeline failure notification would be sent here"
        # Add your notification logic (Slack, email, etc.)
      fi

# ======================================
# Manual Jobs
# ======================================

update-baseline:
  stage: deploy
  image: dart:stable
  timeout: 5m
  script:
    - echo "🔄 Updating performance baseline..."
    - |
      # Update baseline with current performance metrics
      dart run bin/flutter_keycheck.dart \
        --keys test/golden_workspace/expected_keycheck.json \
        --path test/golden_workspace > /dev/null 2>&1
      echo "✅ Baseline updated"
  when: manual
  only:
    - main