name: flutter_keycheck
description: Enterprise-grade Flutter widget key analyzer with premium HTML reports, advanced analytics, and glassmorphism UI. Perfect for QA automation teams.
version: 3.1.9
repository: https://github.com/1nk1/flutter_keycheck
homepage: https://github.com/1nk1/flutter_keycheck
documentation: https://pub.dev/packages/flutter_keycheck
issue_tracker: https://github.com/1nk1/flutter_keycheck/issues

topics:
  - flutter
  - automation
  - testing
  - cli
  - static-analysis

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ">=2.4.2 <3.0.0"
  analyzer: ^7.7.1
  crypto: ">=3.0.3 <4.0.0"
  path: ">=1.9.0 <2.0.0"
  yaml: ">=3.1.2 <4.0.0"

dev_dependencies:
  test: ^1.25.0
  collection: ^1.18.0
  lints: ^5.1.1

executables:
  flutter_keycheck: flutter_keycheck

# Screenshots for pub.dev (if you have any)
# screenshots:
#   - description: 'CLI output showing key validation results'
#     path: screenshots/cli_output.png
#   - description: 'Configuration file example'
#     path: screenshots/config_example.png

# Platforms supported
platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:
# What gets published to pub.dev
# The .pubignore file controls what gets excluded