name: flutter_keycheck
description: Enterprise-grade Flutter widget key analyzer with premium HTML reports, advanced analytics, and glassmorphism UI. Perfect for QA automation teams.
version: 3.0.4
repository: https://github.com/1nk1/flutter_keycheck
homepage: https://github.com/1nk1/flutter_keycheck
documentation: https://pub.dev/packages/flutter_keycheck
issue_tracker: https://github.com/1nk1/flutter_keycheck/issues

topics:
  - flutter
  - automation
  - testing
  - cli
  - static-analysis

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  analyzer: ^8.1.1
  crypto: ^3.0.3
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.0
  collection: ^1.18.0
  lints: ^6.0.0

executables:
  flutter_keycheck: flutter_keycheck

# Screenshots for pub.dev (if you have any)
# screenshots:
#   - description: 'CLI output showing key validation results'
#     path: screenshots/cli_output.png
#   - description: 'Configuration file example'
#     path: screenshots/config_example.png

# Platforms supported
platforms:
  linux:
  macos:
  windows:
# What gets published to pub.dev
# The .pubignore file controls what gets excluded