name: flutter_keycheck
description: A CLI tool for verifying presence of ValueKey elements and test dependencies in Flutter projects.
version: 1.0.1

homepage: https://github.com/1nk1/flutter_keycheck
repository: https://github.com/1nk1/flutter_keycheck
issue_tracker: https://github.com/1nk1/flutter_keycheck/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  path: ^1.8.3
  glob: ^2.1.2
  ansicolor: ^2.0.1
  cli_util: ^0.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

executables:
  flutter_keycheck: flutter_keycheck
