#!/bin/bash

# Flutter Casino Demo - Comprehensive Validation Execution Script
# Generated by Flutter KeyCheck Orchestrator
# This script executes the complete validation workflow for all 16 automation keys

set -e  # Exit on any error

# Colors for output formatting
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script configuration
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_DIR="$PROJECT_DIR/validation_reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

echo -e "${PURPLE}🎰 Flutter Casino Demo - Comprehensive Validation Workflow${NC}"
echo -e "${PURPLE}================================================================${NC}"
echo -e "Project: $(basename "$PROJECT_DIR")"
echo -e "Timestamp: $(date)"
echo -e "Report Directory: $REPORT_DIR"
echo ""

# Create reports directory
mkdir -p "$REPORT_DIR"

# Phase 1: Environment Validation
echo -e "${BLUE}🔍 Phase 1: Environment Validation${NC}"
echo -e "----------------------------------------"

# Check Flutter installation
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}❌ Flutter not found. Please install Flutter SDK.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Flutter SDK: $(flutter --version | head -n1)${NC}"

# Check if we're in a Flutter project
if [ ! -f "pubspec.yaml" ]; then
    echo -e "${RED}❌ Not in a Flutter project directory${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Flutter project detected${NC}"

# Check Flutter KeyCheck availability
if ! command -v flutter_keycheck &> /dev/null; then
    echo -e "${YELLOW}⚠️  Flutter KeyCheck not globally installed. Installing...${NC}"
    dart pub global activate flutter_keycheck
    export PATH="$PATH:$HOME/.pub-cache/bin"
fi

echo -e "${GREEN}✅ Flutter KeyCheck available${NC}"
echo ""

# Phase 2: Dependencies Setup
echo -e "${BLUE}🔧 Phase 2: Dependencies Setup${NC}"
echo -e "----------------------------------------"

# Get Flutter dependencies
echo -e "${CYAN}Installing Flutter dependencies...${NC}"
flutter pub get

# Add integration_test if not present
if ! grep -q "integration_test:" pubspec.yaml; then
    echo -e "${YELLOW}⚠️  Adding integration_test dependency...${NC}"
    flutter pub add integration_test --dev
fi

echo -e "${GREEN}✅ Dependencies configured${NC}"
echo ""

# Phase 3: Static Key Validation
echo -e "${BLUE}🔍 Phase 3: Static Key Validation${NC}"
echo -e "----------------------------------------"

echo -e "${CYAN}Executing comprehensive key scan...${NC}"

# Run flutter_keycheck with comprehensive configuration
if [ -f "expected_keys_comprehensive.yaml" ]; then
    flutter_keycheck \
        --config expected_keys_comprehensive.yaml \
        --report json \
        --output "$REPORT_DIR/key_validation_$TIMESTAMP.json" \
        --verbose || {
        echo -e "${RED}❌ Static key validation failed${NC}"
        exit 1
    }
    
    echo -e "${GREEN}✅ Static key validation completed${NC}"
    echo -e "Report: $REPORT_DIR/key_validation_$TIMESTAMP.json"
else
    echo -e "${YELLOW}⚠️  Comprehensive config not found, using default scan...${NC}"
    flutter_keycheck \
        --report json \
        --output "$REPORT_DIR/key_validation_default_$TIMESTAMP.json"
fi

echo ""

# Phase 4: Integration Test Validation  
echo -e "${BLUE}🧪 Phase 4: Integration Test Validation${NC}"
echo -e "----------------------------------------"

if [ -d "integration_test" ] && [ -f "integration_test/casino_automation_test.dart" ]; then
    echo -e "${CYAN}Executing comprehensive integration tests...${NC}"
    
    # Run integration tests with detailed output
    flutter test integration_test/casino_automation_test.dart \
        --reporter expanded \
        --timeout 120s > "$REPORT_DIR/integration_test_$TIMESTAMP.log" 2>&1 || {
        echo -e "${RED}❌ Integration tests failed${NC}"
        echo -e "Check log: $REPORT_DIR/integration_test_$TIMESTAMP.log"
        exit 1
    }
    
    echo -e "${GREEN}✅ Integration tests completed successfully${NC}"
    echo -e "Test log: $REPORT_DIR/integration_test_$TIMESTAMP.log"
else
    echo -e "${YELLOW}⚠️  Integration tests not found, skipping...${NC}"
fi

echo ""

# Phase 5: Performance Validation
echo -e "${BLUE}⚡ Phase 5: Performance Validation${NC}"
echo -e "----------------------------------------"

echo -e "${CYAN}Analyzing application performance...${NC}"

# Build for performance testing
flutter build web --web-renderer html --dart-define=FLUTTER_WEB_USE_SKIA=false > /dev/null 2>&1 || {
    echo -e "${YELLOW}⚠️  Web build failed, using debug mode${NC}"
}

# Run performance benchmark if available
if [ -f "test/performance_test.dart" ]; then
    flutter test test/performance_test.dart --reporter json > "$REPORT_DIR/performance_$TIMESTAMP.json"
    echo -e "${GREEN}✅ Performance tests completed${NC}"
else
    echo -e "${YELLOW}⚠️  Performance tests not available${NC}"
fi

echo ""

# Phase 6: Report Generation
echo -e "${BLUE}📊 Phase 6: Report Generation${NC}"
echo -e "----------------------------------------"

# Generate comprehensive validation report
REPORT_FILE="$REPORT_DIR/comprehensive_validation_report_$TIMESTAMP.md"

cat > "$REPORT_FILE" << EOF
# Flutter Casino Demo - Comprehensive Validation Report

**Generated:** $(date)  
**Project:** Flutter Casino Demo with Premium Glassmorphism UI  
**Validation Scope:** 16 Automation Keys across 4 Game Modules

## 📋 Executive Summary

### Validation Results
$(if [ -f "$REPORT_DIR/key_validation_$TIMESTAMP.json" ]; then
    echo "- ✅ Static Key Validation: COMPLETED"
    echo "- 📊 Total Keys Detected: $(grep -o '"key"' "$REPORT_DIR/key_validation_$TIMESTAMP.json" | wc -l 2>/dev/null || echo "N/A")"
else
    echo "- ⚠️  Static Key Validation: SKIPPED"
fi)

$(if [ -f "$REPORT_DIR/integration_test_$TIMESTAMP.log" ]; then
    if grep -q "All tests passed" "$REPORT_DIR/integration_test_$TIMESTAMP.log" 2>/dev/null; then
        echo "- ✅ Integration Tests: PASSED"
    else
        echo "- ❌ Integration Tests: FAILED"
    fi
else
    echo "- ⚠️  Integration Tests: SKIPPED"
fi)

### Key Coverage Analysis

#### Critical Keys (Must Pass)
- Navigation: \`slotsGameCard\`, \`rouletteGameCard\`, \`blackjackGameCard\`
- Slots: \`spinButton\`
- Roulette: \`redBet\`, \`blackBet\`, \`spinRouletteButton\`
- Blackjack: \`dealButton\`, \`hitButton\`, \`standButton\`

#### High Priority Keys  
- Demo System: \`demoModeCard\`, \`runDemoButton\`
- Game Control: \`newGameButton\`

#### Medium Priority Keys
- Betting Controls: \`decreaseBetButton\`, \`increaseBetButton\`

### Quality Metrics
- **Target Reliability:** >95% test pass rate
- **Target Performance:** <60 second test execution
- **Key Detection Accuracy:** >99% detection rate
- **False Positive Rate:** <2% target

## 📁 Generated Reports

$(ls -la "$REPORT_DIR"/*$TIMESTAMP* 2>/dev/null | while read -r line; do
    filename=$(basename "$(echo "$line" | awk '{print $NF}')")
    echo "- 📄 \`$filename\`"
done)

## 🎯 Recommendations

### For QA Teams
1. **Critical Path Testing**: Focus on navigation and core game actions
2. **Automated Regression**: Use integration tests for continuous validation  
3. **Performance Monitoring**: Track test execution time trends

### For Development Teams  
1. **Key Consistency**: Maintain consistent key naming patterns
2. **Test Coverage**: Ensure all new features include automation keys
3. **Performance**: Monitor app performance impact of key additions

## 🔗 Next Steps

1. **CI/CD Integration**: Add validation to pipeline
2. **Monitoring Setup**: Implement key validation alerts
3. **Documentation**: Keep key inventory updated
4. **Training**: QA team training on comprehensive test suite

---
*Generated by Flutter KeyCheck Orchestrator - Enterprise Automation Validation*
EOF

echo -e "${GREEN}✅ Comprehensive report generated${NC}"
echo -e "Report: $REPORT_FILE"

echo ""

# Phase 7: Summary and Recommendations
echo -e "${BLUE}🎯 Phase 7: Validation Summary${NC}"
echo -e "========================================="

echo -e "${GREEN}✅ Validation Workflow Completed Successfully!${NC}"
echo ""

echo -e "${PURPLE}📊 Results Summary:${NC}"
echo -e "  • Static Key Validation: $([ -f "$REPORT_DIR/key_validation_$TIMESTAMP.json" ] && echo "COMPLETED" || echo "SKIPPED")"
echo -e "  • Integration Tests: $([ -f "$REPORT_DIR/integration_test_$TIMESTAMP.log" ] && echo "EXECUTED" || echo "SKIPPED")"
echo -e "  • Performance Analysis: COMPLETED"
echo -e "  • Comprehensive Report: GENERATED"

echo ""
echo -e "${PURPLE}📁 All Reports Available In:${NC}"
echo -e "  $REPORT_DIR"

echo ""
echo -e "${PURPLE}🚀 Quick Commands for Manual Verification:${NC}"
echo -e "${CYAN}  # Run static validation:${NC}"
echo -e "  flutter_keycheck --config expected_keys_comprehensive.yaml"
echo ""
echo -e "${CYAN}  # Run integration tests:${NC}"  
echo -e "  flutter test integration_test/casino_automation_test.dart"
echo ""
echo -e "${CYAN}  # View latest report:${NC}"
echo -e "  cat '$REPORT_FILE'"

echo ""
echo -e "${GREEN}🎰 Flutter Casino Demo validation orchestration complete!${NC}"
echo -e "${PURPLE}Enterprise-grade automation validation ready for QA teams.${NC}"