name: RC Feedback
description: Report feedback for release candidate testing
title: "[RC Feedback]: "
labels: ["rc-feedback", "v3.0.0-rc.1"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for testing v3.0.0-rc.1! Please provide details about your experience.

  - type: input
    id: command
    attributes:
      label: Command used
      description: Full command with all flags
      placeholder: flutter_keycheck scan --path . --report json --strict
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output summary
      description: Paste the summary section and exit code
      placeholder: |
        {
          "summary": {
            "coverage": 0.85,
            "total_keys": 142
          }
        }
        Exit code: 0
    validations:
      required: true

  - type: input
    id: performance
    attributes:
      label: Runtime & JSON size
      description: Execution time and output file size
      placeholder: "1.8s, 42 KB"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected vs actual
      description: What did you expect vs what happened?
      placeholder: |
        Expected: All keys detected
        Actual: Missing KeyConstants patterns
    validations:
      required: true

  - type: textarea
    id: json_sample
    attributes:
      label: JSON sample
      description: Relevant snippet from JSON output (optional)
      render: json
    validations:
      required: false

  - type: input
    id: project_size
    attributes:
      label: Project size
      description: Approximate LOC and widget count
      placeholder: "50K LOC, 200 widgets"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this issue?
      options:
        - P0 - Blocker
        - P1 - Critical
        - P2 - Major
        - P3 - Minor
      default: 2
    validations:
      required: true