name: Basic Flutter KeyCheck Validation

on:
  push:
    branches: [main, develop, flutter_keycheck_v3]
    tags: ['v*']
  pull_request:
    branches: [main, develop, flutter_keycheck_v3]

jobs:
  basic-test:
    name: Basic Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

      - name: Test flutter_keycheck CLI
        run: |
          dart compile exe bin/flutter_keycheck.dart -o flutter_keycheck_test
          ./flutter_keycheck_test --help

  validate-keycheck:
    name: KeyCheck Self-Validation
    runs-on: ubuntu-latest
    needs: basic-test
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Build CLI
        run: dart compile exe bin/flutter_keycheck.dart -o flutter_keycheck

      - name: Self-validate project
        run: |
          ./flutter_keycheck scan --project-root . --report text > scan_result.txt
          cat scan_result.txt
          echo "✅ Self-validation completed"

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: keycheck-scan-results
          path: scan_result.txt
          retention-days: 7