name: Flutter Keys Validation (Legacy)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.dart'
      - '.flutter_keycheck.yaml'
      - 'baseline.json'

jobs:
  validate-keys:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history for baseline comparison
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install Flutter KeyCheck
      run: dart pub global activate flutter_keycheck
    
    - name: Download baseline from main branch
      run: |
        git show origin/main:baseline.json > baseline-main.json || echo '{"metadata": {}, "keys": []}' > baseline-main.json
    
    - name: Generate current baseline
      run: |
        flutter_keycheck baseline create \
          --project-root . \
          --output baseline-current.json
    
    - name: Compare baselines
      id: diff
      run: |
        flutter_keycheck diff \
          --baseline-old baseline-main.json \
          --baseline-new baseline-current.json \
          --report markdown \
          --report json \
          --output diff-report
        echo "EXIT_CODE=$?" >> $GITHUB_ENV
    
    - name: Validate against baseline
      id: validate
      run: |
        flutter_keycheck validate \
          --project-root . \
          --baseline baseline-main.json \
          --fail-on-lost \
          --fail-on-rename \
          --max-drift 10 \
          --report junit \
          --report json
      continue-on-error: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: key-validation-reports
        path: |
          reports/*.json
          reports/*.xml
          reports/*.md
          reports/*.html
    
    - name: Publish test results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: reports/validation-report.xml
        check_name: Flutter Key Validation Results
    
    - name: Comment PR with diff report
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔑 Flutter Keys Validation Report\n\n';
          
          // Read the markdown diff report
          try {
            const diffReport = fs.readFileSync('diff-report.md', 'utf8');
            comment += diffReport;
          } catch (e) {
            comment += '⚠️ Unable to generate diff report\n';
          }
          
          // Add validation status
          const validationExitCode = '${{ steps.validate.outcome }}';
          if (validationExitCode === 'success') {
            comment += '\n\n✅ **Validation Status**: All checks passed';
          } else {
            comment += '\n\n❌ **Validation Status**: Some checks failed';
            comment += '\n\nPlease review the changes and ensure critical keys are not lost.';
          }
          
          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Flutter Keys Validation Report')
          );
          
          // Update or create comment
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          }
    
    - name: Check validation status
      if: steps.validate.outcome == 'failure'
      run: |
        echo "❌ Flutter key validation failed!"
        echo "Please review the PR comment for details."
        exit 1

  update-baseline:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install Flutter KeyCheck
      run: dart pub global activate flutter_keycheck
    
    - name: Update baseline
      run: |
        flutter_keycheck baseline create \
          --project-root . \
          --output baseline.json \
          --auto-tags
    
    - name: Commit updated baseline
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add baseline.json
        git diff --staged --quiet || git commit -m "chore: update key baseline [skip ci]"
        git push