name: V3 Verification

on:
  push:
    branches: ["flutter_keycheck_v3", "main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  verify-v3:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run analyzer
      run: dart analyze --no-fatal-warnings
    
    - name: Activate flutter_keycheck v3
      run: dart pub global activate --source path .
    
    - name: Verify version
      run: |
        flutter_keycheck -V
        flutter_keycheck --help
    
    - name: Run scan command
      run: |
        flutter_keycheck scan \
          --report json,junit,md \
          --out-dir reports \
          --verbose
    
    - name: Run validate command
      id: validate
      run: |
        flutter_keycheck validate \
          --strict \
          --fail-on-lost \
          --fail-on-extra \
          --protected-tags critical,aqa
        echo "exit_code=$?" >> $GITHUB_OUTPUT
    
    - name: Generate coverage report
      run: |
        flutter_keycheck report \
          --format lcov \
          --out-dir coverage
    
    - name: Upload scan artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scan-reports-${{ github.sha }}
        path: |
          reports/
          coverage/
        retention-days: 30
    
    - name: Post PR comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('reports/report.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });
    
    - name: Check exit codes
      run: |
        echo "Validate exit code: ${{ steps.validate.outputs.exit_code }}"
        if [ "${{ steps.validate.outputs.exit_code }}" -eq 1 ]; then
          echo "❌ Policy violation detected"
          exit 1
        elif [ "${{ steps.validate.outputs.exit_code }}" -eq 0 ]; then
          echo "✅ All validations passed"
        else
          echo "⚠️ Unexpected exit code"
          exit 1
        fi

  test-golden-workspace:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Setup golden workspace
      run: |
        cd test/golden_workspace
        dart pub get
    
    - name: Run golden tests
      run: |
        cd test/golden_workspace
        dart test test/golden_test.dart
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: golden-test-results-${{ github.sha }}
        path: test/golden_workspace/reports/
        retention-days: 7

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart-version: ['3.5.0', 'stable', 'beta']
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.dart-version }}
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run integration tests
      run: |
        # Test v3 CLI commands
        dart run bin/flutter_keycheck_v3.dart --version
        dart run bin/flutter_keycheck_v3.dart scan --help
        dart run bin/flutter_keycheck_v3.dart validate --help
        
        # Test in golden workspace
        cd test/golden_workspace
        dart pub get
        dart run ../../bin/flutter_keycheck_v3.dart scan --report json
        dart run ../../bin/flutter_keycheck_v3.dart baseline create
        dart run ../../bin/flutter_keycheck_v3.dart validate
    
    - name: Test deterministic exit codes
      run: |
        set +e  # Don't exit on error
        
        # Test success (0)
        dart run bin/flutter_keycheck_v3.dart --version
        [ $? -eq 0 ] && echo "✅ Exit code 0 works" || exit 1
        
        # Test policy violation (1) - would fail if critical keys missing
        cd test/golden_workspace
        dart run ../../bin/flutter_keycheck_v3.dart validate --fail-on-extra --strict || true
        EXIT_CODE=$?
        [ $EXIT_CODE -eq 0 ] || [ $EXIT_CODE -eq 1 ] && echo "✅ Policy exit codes work" || exit 1